### ISSUE TITLE
Unable to compile the complete app

### ISSUE THREAD

**Issue by subhamagr** [mz026/universal-redux-template#10]
Yesterday i started using your boilerplate and it works fine when running using 
```shell
npm start
```

But i complied it using the command:
```shell
NODE_ENV=production npm run build
```

It creates a dist folder with everything except the node server file and the index.html file. So i am not able to create a dist folder so that i can deploy.
How do i resolve this issue?

**Comment by mz026** [comment]
@subhamagr The server side code of this app is run directly without any build process. So after the building command, which bundles the code for browser, you can start the server using `NODE_PATH=app/ NODE_ENV=production node app/server`

I'll add doc addressing this part, here's the issue tracking it: https://github.com/mz026/universal-redux-template/issues/11

**Comment by subhamagr** [comment]
Works Fine! thanks!
