### ISSUE TITLE
Tests do not run

### ISSUE THREAD

**Issue by jbuffin** [mz026/universal-redux-template#17]
`npm test` has the following error:
`Error: cannot resolve path (or pattern) ''app/spec/**/*.test.js''`

I am using Windows. It seems like the single quotes are not necessary (and cause issues) around the path/pattern for the test target.

Fixed with https://github.com/mz026/universal-redux-template/pull/16

**Comment by mz026** [comment]
Thanks for pointing it out! The [single quotes are necessary on unix-like machine](https://github.com/mochajs/mocha/issues/1115).
I left this setting on [documentation](https://github.com/mz026/universal-redux-template#npm-test).
