### ISSUE TITLE
Error: Couldn't find preset "stage-1" relative to directory

### ISSUE THREAD

**Issue by kishanj918** [mz026/universal-redux-template#18]
i ran NODE_ENV=production npm install command and installed node modules then i ran NODE_ENV=production NODE_PATH=./app node app/server command.. But it's giving me Error: Couldn't find preset "stage-1" relative to directory. Any ideas?

My .babelrc is like following.
{
  "presets": ["es2015", "react","stage-1"],
  "env": {
    "test": {
      "plugins": [ "babel-plugin-rewire" ]
    }
  }
}

**Comment by mz026** [comment]
I think you will need to install [`babel-preset-stage-1`](https://babeljs.io/docs/plugins/preset-stage-1/) before you can use it with the `.babelrc` you provided. It's not in current dependencies as the [current .babelrc](https://github.com/mz026/universal-redux-template/blob/master/.babelrc) doesn't include it.

**Comment by kishanj918** [comment]
i installed babel-preset-stage-1. but still getting the same error.

**Comment by kishanj918** [comment]
@mz026  thanks that worked... Now i am getting an error like following.. can you help?

 scriptSrcs = ['/' + assets.vendor.js, '/' + assets.app.js];
                                                        ^
TypeError: Cannot read property 'js' of undefined

**Comment by mz026** [comment]
@kishanj918 Seems some `entry` in your `webpack.config.js` are missing. There should be `app`, and `vendor`. Could you provide your `webpack.config.js`?
Also, what's the content in your `dist/webpack-assests.json`?

**Comment by kishanj918** [comment]
@mz026   yes the problem with webpack.config.js.. thanks..

**Comment by mz026** [comment]
@kishanj918 no problem! good luck :smile:

**Comment by kishanj918** [comment]
@mz026  one more question. How can i use forever or pm2 to run (NODE_ENV=production NODE_PATH=./app node app/server) command?

**Comment by juandata** [comment]
run `npx babel-upgrade `
