### ISSUE TITLE
checksum was invalid

### ISSUE THREAD

**Issue by subhamagr** [mz026/universal-redux-template#22]
I want to perform this check if the current route is '/' and change some styling... so i tried doing:
```javascript
<div style={(global.location && global.location.pathname ===  '/' ) ? style1 : style2}></div>
```

But it gives me checksum warning. something like... 
 React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) 0,0,0,0);box-shadow:none;border-radius:0
 (server) 0,0,0,0);box-shadow:0 1px 6px rgba(0, 0,

how am i suppose to solve this?

**Comment by subhamagr** [comment]
how to configure redux with react-router using react-router-redux?

**Comment by mz026** [comment]
@subhamagr For the invalid checksum, the warning happens when the html you served from server side is not the same as the one generated in the initial rendering on client side. For your case, I think you can check if `global.location && global.location.pathname ===  '/'` are the same on server side and client side.

**Comment by mz026** [comment]
For the `react-router-redux` question, I haven't used it in my projects. I think the [real-world example of redux repo](https://github.com/reactjs/redux/tree/master/examples/real-world) might be a good reference.

**Comment by subhamagr** [comment]
how do I check that?

**Comment by mz026** [comment]
I would do something like `console.log(global.location, global.location.pathname)` on both client-side and server-side to see the difference.

**Comment by subhamagr** [comment]
I did console.log inside the match function in server.js file
```javascript
match({routes, location}, (error, redirectLocation, renderProps) => {
        console.log(location);
        //...
})
```

As soon as i request a url, it displays correctly. But at the same time i did 
```jaavscript
componentWillMount() { console.log(global.location) }
```

it displays undefined in the server console but displays correctly on browser console.
What can I do now?
