### ISSUE TITLE
Trying to populate redux store in onEnter hook of react router.

### ISSUE THREAD

**Issue by kishanj918** [mz026/universal-redux-template#23]
I want to call static fetchData of component in onEnter hook so that i can populate the store with data.
i just don't know how can i do this. or any other way i can load the data before component render will be helpful..
I am trying to do this as following..

Here is my route.
`<Route path='/edit/profile' component={requireAuth(EditProfile)} onEnter={loadData}/>`
 here is my loadData function 
`function loadData(nextState, replace,callback) {
  if (nextState && nextState.routes.length > 0) {
      console.log(nextState)
    callback()
  }
}`

**Comment by mz026** [comment]
@kishanj918 How about doing that in `componentDidMount()` ?

**Comment by kishanj918** [comment]
@mz026  i want to load the data before component will render.

**Comment by mz026** [comment]
@kishanj918 Could you provide more context about your use case? Would you like to load the data on server side (while doing universal rendering) or on the client side (while route changing)?

**Comment by kishanj918** [comment]
@mz026  i managed to load data on onEnter hook but i am going through one issue. [https://github.com/reactjs/redux/issues/1732](url) would you mind have a look at this.?
