### ISSUE TITLE
Not an issue - Page refresh scenario

### ISSUE THREAD

**Issue by sabha** [mz026/universal-redux-template#24]
Many Thanks for putting it together. Please clarify , when the user refresh the page from this route `http://localhost:3000/questions`. Technically a request will be made to the server and express will call the  `/questions `api internally and send the rendered HTML along with data and routing. But I see a request from the client to /questions api. Unsure why there is a data fetching call from the client when the user refresh the page.

**Comment by mz026** [comment]
Hi @sabha , yes, the network behaved just as you described. For the `questions` route, there're two cases in which the app will send request to server: 

1. when doing isomorphic rendering on server side.
2. when route changes on client side

Under the page reload situation, the request you saw was the case 2 above.
Actually it might be an extraneous request as the one made on the server side, we can handle it in the `componentWillReceiveProps`. For the simplicity I just leave it like what you saw now.

**Comment by sabha** [comment]
Got it , so we are calling the API twice one on the server side and another one is on the client once after server Served the rendered html? Could you please share which is the best practice to handle server side rendering. 
I understood the isomorphic code such as static data fetch , routes , redux actions , but not server side rendering and SPA.
Is there any downside if we architect React apps in a way we do in php or java jsp world rather than mixing both SPA and server side rendering.

**Comment by mz026** [comment]
> so we are calling the API twice one on the server side and another one is on the client once after server Served the rendered html?

Not really, we're calling the API *once* one the server side and another one on the client side.

> Is there any downside if we architect React apps in a way we do in php or java jsp world rather than mixing both SPA and server side rendering.

I my opinion, the primary advantage of doing isomorphic rendering with React is that we can create an SEO friendly SPA webapp without having to maintain two separate code bases/logic (one for SPA, another one for server rendering part).

On the other hand, isomorphic rendering comes with the cost of the complexity on the combination of  server-rendering part and front-end logic(such as the stuff in [server.js](https://github.com/mz026/universal-redux-template/blob/master/app/server/server.js).) That is, we need to find a way to share code between client side and server side. But the good news is that in most cases, the complexity won't grow with your app, it's something like an infrastructure that you build once and you can use it all over you dev cycle.

**Comment by sabha** [comment]
Many Thanks, finally I understood a lot after going through your code. Found  the difference between universal rendering and isomorphic app. I want to highly rely on server side rendering because of authentication , based on the user types such as Admin , Director , Parents , etc I want to server their ROUTES and this package also helped.
https://www.npmjs.com/package/redux-async-connect
