### ISSUE TITLE
Unexpected character '�' (1:0) [0] > 1 | �PNG

### ISSUE THREAD

**Issue by sahilCampusdiaries** [mz026/universal-redux-template#25]
Hello,

I am trying to use this boiler plate in my project, but I got this issue Unexpected character '�' (1:0)
[0] > 1 | �PNG, How can i resolved this issue, Kindly guide me.

**Comment by mz026** [comment]
Hi,

May I know how to reproduce this issue and the versions of your `node` and `npm`?
I cloned the repo from scratch, install dependencies and ran `npm start` and everything looks fine.

**Comment by sahilCampusdiaries** [comment]
Hi,

I am trying to add img tag then It is showing errors.
like <img scr={require('../imagepath/a.png')}/>

**Comment by sahilCampusdiaries** [comment]
`<img width="262" height="262" src={require("../../statics/images/team/SumitSaurav.png")} alt="" />`

**Comment by mz026** [comment]
I didn't use webpack to handle images in this boilerplate as it slows down the build time. To achieve what you want in the code snippet, try setting up the static path from express and access it from express.

Such as:

```javascript
//express
server.use(Express.static(path.join(__dirname, '../..', 'statics')))

//component
<img width="262" height="262" src="/images/team/SumitSaurav.png" alt="" />
```

I'm going to close this issue for now.

**Comment by sahilCampusdiaries** [comment]
Thanks,
