### ISSUE TITLE
Instructions on installing vendor packages

### ISSUE THREAD

**Issue by dlombardi** [mz026/universal-redux-template#27]
It'd be nice if the readme included steps to install vendor packages. I'm not sure where the vendor.js in the dist is sourcing from or how to include packages in there.

**Comment by mz026** [comment]
Cool, I'll add it later, thanks!

**Comment by mz026** [comment]
It's added [here](https://github.com/mz026/universal-redux-template#vendor-scripts), thanks for pointing it out. I'm going to close this issue.
