### ISSUE TITLE
Posting form data to the backend using the api setup

### ISSUE THREAD

**Issue by sschenk** [mz026/universal-redux-template#28]
How would you go about Implementing a post request using this repo. api setup?
I've been examining the api.js and server.js files, and I'm not completely sure how should I send the form's data to the server using the promise system you've setup.

**Comment by mz026** [comment]
It can be done by setting the `method` to `post`, and add a `body` field if any. The code in action creator would be look like this:

```javascript
// in an action creator
  return {
    [CALL_API]: {
      method: 'post',
      path: '/api/questions',
      body: {
        bodyKey: 'body-val'
      },
      successType: CREATED_QUESTION
    }
  }
```
