### ISSUE TITLE
call ajax before render (on server-side)

### ISSUE THREAD

**Issue by matiishyn** [mz026/universal-redux-template#29]
Hi.
Thanks for the great template!

Is it possible to call ajax (using redux of course) before render? on the server-side

I'm using your template and inside component's `willMount` or `didMount` I'm dispatching action which will make the ajax, like here: https://github.com/mz026/universal-redux-template/blob/master/app/containers/Questions.js#L14

But when I refresh page then page is firstly generated and rendered without data and after some time data is filled

The same result on `/questions` page. It's rendered without data and data is filled later.
But is it possible to get and render already filled component?

**Comment by matiishyn** [comment]
Seems like it supposed to work like that because you have this component's method: `static fetchData` (https://github.com/mz026/universal-redux-template/blob/master/app/containers/Questions.js#L9)
and server is checking if that method exists. 
But it doesn't work.

Could you please take a look. I'm trying to resolve that but it's really difficult

**Comment by mz026** [comment]
Hi @matiishyn , thanks for trying it out!

I can't reproduce the issue you mentioned on my end.
Are you on `master` branch of `universal-redux-template`? (which has hash code `2bd6537`)
Also, may I have your node version?

**Comment by matiishyn** [comment]
Seems that I had an error in my code. My bad
Thanks for checking and sorry for that :)
