### ISSUE TITLE
`WrappedComponent` reference is undefined

### ISSUE THREAD

**Issue by manakor** [mz026/universal-redux-template#3]
When I try to find a component in [`app/server/server.js`](https://github.com/mz026/universal-redux-template/blob/2967d93a8adb35f7af9a8dd8cda8240e1567079d/app/server/server.js#L84), its `WrappedComponent` reference is always undefined:
````js
let comp = renderProps.components[renderProps.components.length - 1].WrappedComponent;
```` 

When trying to output found component, it is logged as:
````js
console.log(renderProps.components[renderProps.components.length - 1])
// [Function: ComponentName]
````

So the component seems to be found, but there's no way to access its `WrappedComponent` reference, and, obviously, not possible to access `fetchData()` method to get data it requires to render with a server.

**Comment by manakor** [comment]
It seems the issue appears only in my local app inherited from [react-redux-starter-kit](https://github.com/davezuko/react-redux-starter-kit), since this app outputs found component differently and correctly:
````js
console.log(renderProps.components[renderProps.components.length - 1])
// [Function: Connect]
// displayName: 'Connect(Question)',
// WrappedComponent: [Function: Question],
// ...
````

@mz026, do you might know what could be the reason I'm not getting `[Function Connect]` as a found component, which has a reference in `WrappedComponent`?

**Comment by mz026** [comment]
@manakor The `WrappedComponent` is created by `connect` of `react-redux`. `universal-redux-template` assumes all the components doing `fetchData` are "smart component" (wrapped by `connect`) of redux. Was the matched component in your route a `connect`-ed one?

**Comment by manakor** [comment]
@mz026, it seems `match` method of `react-router` identifies the component incorrectly for me.
Here's the hierarchy [react-redux-starter-kit](https://github.com/davezuko/react-redux-starter-kit) offers to have:

````js
<Route path='/' component={CoreLayout}>
    <IndexRoute component={StreamView} />
  </Route>
````

Where `StreamView` is a "dumb component":
````js
export class Stream extends React.Component {
  props: Props;

  render () {
    return (
      <div>
        <StreamContainer />
      </div>
    )
  }
}
```` 

Where `StreamContainer` is "smart component":
````js
export class StreamContainer extends React.Component {
  props: Props;

  static fetchData ({ store }) {
    return store.dispatch(loadPosts())
  }

  componentDidMount () {
    this.props.loadPosts()
  }

  render () {
    return (
      <div>
        <Stream posts={this.props.posts} />
        <PostComposer onSubmit={this.props.submitPost} />
      </div>
    )
  }
}

...

export default connect(mapStateToProps, { loadPosts })(StreamContainer)
````

But `match` returns me my `StreamView` component (which is "dumb"), instead of it's children `StreamContainer` component:
````js
console.log(renderProps.components[renderProps.components.length - 1])
// [Function: Stream]
````

Probably, something wrong with components hierarchy?

**Comment by mz026** [comment]
According to your route: ` <IndexRoute component={StreamView} />` , the `match` returning `StreamView` is expected behavior of react-router. `universal-redux-template` was trying to find `fetchData` under `StreamView`.

IMO is a little counter-intuitive to wrap a smart component (`StreamContainer`) into a dump one (`StreamView`). Smart components should be at the higher level than the dumb ones. How about assign `StreamContainer` to the route directly like this?

```javascript
<Route path='/' component={CoreLayout}>
    <IndexRoute component={StreamContainer} />
</Route>
```

**Comment by mz026** [comment]
@manakor did the solution above work?

**Comment by manakor** [comment]
@mz026, yes, absolutely&#8203;_!_ Based on your suggestion we unwrapped first level smart components from dumb components and `match` method from `react-router` started to return exactly what your example does.
