### ISSUE TITLE
nodemon版本不同报错

### ISSUE THREAD

**Issue by baizn** [mz026/universal-redux-template#31]
nodemon 1.6.0 npm start success；
update nodemon to 1.10.0, failed：
![image](https://cloud.githubusercontent.com/assets/9443867/17732459/6cde3e62-64a4-11e6-8da9-db4c8cf859d5.png)

then npm uninstall nodemon , npm install install nodemon@1.6.0,
执行npm start 还是报一样的错！

**Comment by mz026** [comment]
Hi @baizn, could you please

1. switch to node `6.1.0`
2. remove `node_modules` folder
3. re-install `node_modules` by `npm install`

and see if it works?
