### ISSUE TITLE
webpack isomorphic tools?

### ISSUE THREAD

**Issue by developer239** [mz026/universal-redux-template#34]
Is it possible to implement webpack isomorphic tools?

**Comment by mz026** [comment]
I'm not sure what you meant. Could you please elaborate?

**Comment by michaljarnot** [comment]
I was thinking about using assets like images / css / scss in require() statements in react components. But then I decided to create my own gulp file which was a lot easier.

**Comment by gazatem** [comment]
You can not import any additional file while server side rendering the react. For that reason best  solution is to use webpack-isomorphic-tools 

Here the link of npm: [https://www.npmjs.com/package/webpack-isomorphic-tools](https://www.npmjs.com/package/webpack-isomorphic-tools)
