### ISSUE TITLE
Auth system?

### ISSUE THREAD

**Issue by michaljarnot** [mz026/universal-redux-template#35]
I managed to make simple communication with API. (thanks to your API middleware by the way which is really cool) But I am struggling to share "session information" between client and server. Could you please help me a little to figure out how do I read / write cookies so that both client and server can see them?

The problem is when user refreshes page with F5 or something. Then he looses all of his information.

I know that server has access to cookie via req.cookies but ... I don't understand where should I put logic concerning initial state for users that are already logged in. 

I already spent hours trying to figure out how to do this slowly regreting making isomorphic application. I should have just stayed with client since I am totally new to react.

**Comment by michaljarnot** [comment]
I decided to create custom middleware because of this stackoverflow answer: `http://stackoverflow.com/questions/34038726/redux-router-how-to-replay-state-after-refresh`

**Comment by mz026** [comment]
In our cases, we store the session info in the cookies. In application layer, we place the information in Redux store and pass it to client with [`__REDUX_STATE__`](https://github.com/mz026/universal-redux-template/blob/master/app/server/server.js#L77) 

The process would be like the following:

- when user request the page, our node server would know if the user is logged in or not by `req.cookies`
  - if the user is logged in, server sets the logged-in information as initial state when [configuring the store](https://github.com/mz026/universal-redux-template/blob/master/app/server/server.js#L61)
  - if the user is not logged in, server does nothing
- when the state is [passed to client](https://github.com/mz026/universal-redux-template/blob/master/app/app.js#L14), client can tell if the user is logged in or not.

**Comment by michaljarnot** [comment]
So [here](https://github.com/mz026/universal-redux-template/blob/master/app/server/server.js#L59) I put something like:

```
if(req.cookies.loggedIn) {
const initialState = {auth: {loggedIn = true}}; // auth reducer
let store = configureStore(initialState); } else {
let store = configureStore() }
```

Thank you for your time by the way. I guess I would be able to do this on my own but I do not want to learn any anti-patterns if possible.

**Comment by mz026** [comment]
yes! That's exactly what I meant! :smile:

**Comment by michaljarnot** [comment]
I am so good. :D
