### ISSUE TITLE
How to add Google Analytics?

### ISSUE THREAD

**Issue by pyankoff** [mz026/universal-redux-template#36]
I tried to add `react-ga`, but it throws an error, because `window` is not available on the server. Is it possible to add it only on the client?

**Comment by mz026** [comment]
Hi @pyankoff ,

Conceptually, we want the [`logPageView`](https://github.com/react-ga/react-ga#usage) to do nothing on server side, while function normally on client side.

This can be achieved by:

1. modify [`routes/index.js`](https://github.com/mz026/universal-redux-template/blob/master/app/routes/index.js) by adding a `onUpdate` parameter to be configured in `<Router>`
2. do the normal setting on `react-ga` in [`app.js`](https://github.com/mz026/universal-redux-template/blob/master/app/app.js), which is loaded on client side only. Pass a `logPageView` into [`createRoutes`](https://github.com/mz026/universal-redux-template/blob/master/app/app.js#L28)
3. pass a noob function into [`createRoutes` on server side](https://github.com/mz026/universal-redux-template/blob/master/app/server/server.js#L62), or handle the degenerate case in which no `onUpdate` is given in step 1.

**Comment by pyankoff** [comment]
Hey @mz026 , that works like a charm👍  Thank you so much!
And thanks for the great boilerplate!
