### ISSUE TITLE
Favicon and static assets

### ISSUE THREAD

**Issue by pyankoff** [mz026/universal-redux-template#37]
Hello,
What is the good way to add favicon and static folder to the project so that it works correctly both in dev and in production bundle?
Thanks!

**Comment by mz026** [comment]
Hi @pyankoff ,

One of the ways is to serve it by Express, to achieve that, you want to:

1. create a folder for static assets
2. use [`static` middleware](https://expressjs.com/en/starter/static-files.html) to serve that folder under a url path in [server.js](https://github.com/mz026/universal-redux-template/blob/master/app/server/server.js)
3. create a gulp task to move (with or without [rev](https://github.com/smysnk/gulp-rev-all)) that static folder under `dist` when deploying to production

The setting of step 2 may be branched by `production` and `development` mode, such as:

```javascript
if (process.env === 'production') {
  server.use('/assets', <the-path-under-dist-folder>)
} else {
  server.use('/assets', <the-path-of-assets>)
}
```

With the settings above, we can reference the assets from `/assets/...` in our application.

**Comment by mz026** [comment]
Hello @pyankoff , 

Did the solution above work?

**Comment by pyankoff** [comment]
Hey @mz026, yeah the solution should work, thank you! I'm a little stuck on gulp step, didn't have time to figure it out yet. Can Webpack be used for that?

**Comment by mz026** [comment]
Hi @pyankoff ,

Personally I think webpack is harder to manage than gulp to me (especially when trying to do universal rendering).
Actually I added several gulp tasks handling static assets into current master branch, the tasks also deal with [rev](https://github.com/sindresorhus/gulp-rev) stuff. If you fetch/re-clone the current master, you should see an image on `Intro` page. 

The diff commits are here. https://github.com/mz026/universal-redux-template/compare/2bd6537...feb2f6f

I hope that works for you, and thank you for pointing out this issue, it's indeed a missing piece of this boilerplate!!

**Comment by pyankoff** [comment]
Oh man, thank you so much! Will do that first thing tomorrow. I don't have much experience neither with gulp nor with webpack, just thought that Webpack might be a better option to learn :) 
Thanks again, great project!
