### ISSUE TITLE
Server rendering requests data twice

### ISSUE THREAD

**Issue by stepanh** [mz026/universal-redux-template#38]
It seems unnecessary to redo API call when page was rendered on the server. Maybe `app/containers/Question.js` should check for that like this?

```
  componentDidMount() {
    let { id } = this.props.params
    let { question } = this.props
    let loadedId = question.get('id')

    //if component was server-rendered, no need to reload
    if (loadedId !== id) {
      this.props.loadQuestionDetail({ id })
    }
  }
```

Or, maybe there is a better (less specific) way to do this?

PS: Thanks for the cool boilerplate!

**Comment by mz026** [comment]
Hi @stepanh ,

The way you mentioned is all I can think of currently to avoid the double-query on initial loading.
With what you did in `componentDidMount`, you may also want to clear the local cached data in store in `comopnentWillUnMount` if you want to re-fetch the data when routing to the this route from another one on client side.

**Comment by stepanh** [comment]
Sounds good & appreciate the point about the `componentWillUnmount`. If you want this in the template, I can make a pull request.

**Comment by mz026** [comment]
yeah sure, please make a pull request, thanks!!
