### ISSUE TITLE
CALL_API question

### ISSUE THREAD

**Issue by bolicd** [mz026/universal-redux-template#40]
Hello,

first of all, great boilerplate, I like it a lot, so far I havent had problems with it. 

I do have a question regarding CALL_API tho: How do you handle "failure" type. I can see there is  successType, which will be executed if call is success but is there any failureType which will be executed if api call fails? 

Thank you

**Comment by mz026** [comment]
Hello @bolicd ,
Thanks for checking out!

Yes! There is an options called `errorType` (which is a constant just like `successType`) and another one called `onError`, which is a callback. 
Whenever a request fails, an action

```javascript
{
  type: errorType,
  error: errorObjectOfSuperAgent,
  // other key-value pairs of original action here
}
``` 

will be dispatched if `errorType` is given in the `CALL_API` action.

After the dispatching, `afterError` will be invoked with `getState` as argument if it is present in `CALL_API` action.

Please refer to the code [here](https://github.com/mz026/universal-redux-template/blob/master/app/middleware/api.js#L58-L79) in api middleware and let me know if it doesn't  help :smile:

**Comment by bolicd** [comment]
Hey, thanks, thats what I was looking for. 👍 

I actually found that 

[CALL_API]: {
      method: 'post',
      path: '/api/test',
      successType: types.SUCCESS,
      errorType: types.FAILED
    }

works nicely as well and might be a bit cleaner.
