### ISSUE TITLE
POST Requests Not Firing?

### ISSUE THREAD

**Issue by NewETown** [mz026/universal-redux-template#42]
I'm a huge fan of this boilerplate but I seem to be having some issues getting POST requests to work. I took a look at some previous issues around POST requests and I seem to be using the middleware properly but I don't see any network activity and nothing is happening (the GETs I've implemented have worked really well!).

Here's the code:

server.post('/api/post', (req, res) => {
  console.log('server post');
  res.status(200).send({status: 'ok'});
})

export const TEST_POST = Symbol('TEST_POST');
export const TEST_POST_ERROR = Symbol('TEST_POST_ERROR');
export function testPost () {
  console.log('Test post action');
  return {
    [CALL_API]: {
      method: 'post',
      path: '/api/post',
      afterSuccess: () => {console.log('test post succes');},
      successType: TEST_POST,
      errorType: TEST_POST_ERROR
    }
  }
}

case ActionType.TEST_POST:
    console.log('Test post success');
    return state;
case ActionType.TEST_POST_ERROR:
    console.log('Test post eror');
    return state;

Any and all suggestions would be very appreciated!

**Comment by NewETown** [comment]
Ah nevermind, I wasn't calling from props. My bad, thanks for the great boilerplate!

**Comment by mz026** [comment]
Thanks for checking out @NewETown ! Let me know if you get any further issue.
