### ISSUE TITLE
How to use with redux thunk?

### ISSUE THREAD

**Issue by fahd** [mz026/universal-redux-template#46]
Apologies for coming here again! I realize I ask a lot of things :(

i just had a quick question about using redux thunk - the middleware api is throwing me off as to how i'm supposed to be making calls and the blog post, although helpful, didn't clear things up with this. I'm basically trying to do a call like this, however the returned dispatch functions never get called. Is there an ideal way to do this or use the middleware in using redux thunk?

```
export function fetchStuff() {
  return function(dispatch, getState) {
    dispatch({
      type: action_types.FETCH_STUFF_PENDING
    });
    
    return database.ref('my_node').once('value').then(function(snapshot) {
      let items = cleanResponse(snapshot.val(), getState());
      let k = '';

      // Add the items to the state.
      dispatch({
        type: action_types.FETCH_STUFF_FULFILLED,
        payload: {
          items: items
        }
      });

    }).catch(function(response) {
      dispatch({
        type: action_types.FETCH_STUFF_REJECTED,
        payload: response
      });
    });
  }
}
```

**Comment by mz026** [comment]
Hi @fahd ,
sorry for my late reply.

I think I need more context about it.
Did you call this action creator through the `fetchData` on server side?
If so, was it the line

```
database.ref('my_node').once('value').then(...)
```
that wasn't called or it was the callback of the `then` that didn't get called?
