### ISSUE TITLE
Can't load css/less in server render

### ISSUE THREAD

**Issue by NgKhanh** [mz026/universal-redux-template#51]
I got problem when try my SSR code, everything is ok but when I import 'style.less' to component, it got error

Here my pagekage.json scripts
 `"prod": "NODE_ENV=production node server.js"`

And in server.js, I add some loader but It dont work
```
require('babel-core/register')({
    presets: ['react', 'es2015', 'stage-2']
})
require('style-loader!css-loader!less-loader')
```
And I think, how to Ignore css/less in component on server rendering?

**Comment by mz026** [comment]
hi @NgKhanh , thanks for checking out!
Currently we use `gulp` and `node-sass` to handle css separately from js files, so `import`-ing (or `require`-ing) any css file in Component does **not** work. Actually, we use webpack to handle the client-side code only.
