### ISSUE TITLE
Gulp Rev Not Working?

### ISSUE THREAD

**Issue by NewETown** [mz026/universal-redux-template#53]
I seem to be having a problem deploying to production. My gulp rev task runs and generates the manifest.json file but doesn't rename the files in assets/ when it places them in server-build. Any idea what I might be overlooking? Currently using NPM to run the deploy process on Mac, same issue on linux

`2017-03-23T18:13:41.743515+00:00 app[web.1]: Error: Cannot find module 'assets/javascripts/material.min.115d3a6a.js'`

assets/javascripts/material.min.js exists, no rev'd version

**Comment by NewETown** [comment]
Nevermind... I didn't understand how the asset pipeline worked. All working now :). It might be nice to provide more clarity in the README, there are a bunch of cool things we can do with an asset system like this but it wasn't immediately obvious how to use it.

**Comment by mz026** [comment]
Sorry for the late reply, :sweat_smile: 
I tried the master branch and it works. Still trying to reproduce the case you mentioned.

Good to know that your code works!

**Comment by NewETown** [comment]
It wasn't an issue with gulp or any of the modules, the problem was understanding how to reference the asset files. For example, I'm using Material UI so I need to include their JS and CSS files, I didn't know where to look to reference them because I wasn't sure how the asset pipeline worked.
