### ISSUE TITLE
Deprecation warnings when trying out template

### ISSUE THREAD

**Issue by bolicd** [mz026/universal-redux-template#56]
Hi , 

i'm considering using this template for the current project im starting to work on however, when trying to run it i get deprecation warnings in Chrome. 
> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
> Warning: RouterContext: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

Is there any planned update to fix this?

Thanks

**Comment by mz026** [comment]
Hi @bolicd ,

Thanks for checking out! The warning came from `react-router` and `react-helmet`. I just released a new version with some packages (including the two) upgraded, so the warning should be gone in the current `master` branch.

Please let me know if the issue persists. Thanks!

**Comment by bolicd** [comment]
Seems to be working now. Thanks!

**Comment by bolicd** [comment]
This works for react-router <4 if im not mistaken.

I've tried making it work with react-router 4.x but it requires significant changes in server.js since RouterContext and match are no longer used.
