### ISSUE TITLE
How can I make chainable API call?

### ISSUE THREAD

**Issue by TylorShin** [mz026/universal-redux-template#7]
I want to do chaining API_CALL actions.

For example, I wrote below code before using this package.

```
export function signIn(currentUser) {
  return {
    type: actionTypes.SIGN_IN,
    currentUser,
  };
}

export function signInTry(email, password) {
  return dispatch =>
    fetch('/api/login', {
      method: 'post',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        email,
        password,
      }),
    })
    .then(res => handleAjaxError(res))
    .then(res => res.json())
    .then((res) => {
      if (res.access_token) {
        localStorage.clear();
        const userInJson = JSON.stringify(res);
        localStorage.setItem('currentUser', userInJson);
      }
      dispatch(signIn(res));

    })
    .catch((error) => {
      console.log(error);
      return;
    });
}
```

this http 'post' method has promise callback to execute the signIn action.

however, I can't figure out how to make these things in this system.

help me please 😂

**Comment by mz026** [comment]
The current implementation you posted looks good to me :smile: 
You're not restricted to the `CALL_API` middleware and can always use other great middlewares like `redux-thunk`. The `signIn` API is kind of a special case than normal API calls to me as it doesn't require authentication mechanisms which we usually want to extract out. So I usually treat singin api differently.

For the side-effects after successful API calls in general (like the local storage part in your code), there's an [`afterSuccess`](https://github.com/mz026/universal-redux-template/blob/master/app/middleware/api.js#L26) option in `API` middleware, which will be invoked with `getState` after API calls returning OK, this is designed for side-effects after API calls.

**Comment by TylorShin** [comment]
Thx! I'll try!

then, as you said, if I don't need SSR, (ex: HTTP post method or put method...) 
can I use 'dispatch' and redux-thunk as normal redux-react system?

**Comment by mz026** [comment]
Of course you can!! :smiley:

**Comment by mz026** [comment]
@TylorShin if this issue is solved, could you please close it? thanks!
